### ISSUE TITLE
Link to the project page is not displayed

### ISSUE THREAD

**Issue by XelaNimed** [raphaelm22/jquery.serializeToJSON#11]
I'm using a plugin in the ASP.Net Core 2 project (installed using bower). My problem is that link to GitHub not displayed in the description of the bower package. 
I understand that this is a trifle, but it is not entirely convenient to look for a project on GitHub every time. Maybe it makes sense to adjust bower.json for support in Visual Studio?

**Comment by raphaelm22** [comment]
Hi @XelaNimed 

I had already noticed this problem and had forgotten to analyze, believing it to be because the description has more than 140 characters.

Thanks for letting me know.

**Comment by raphaelm22** [comment]
I noticed that the plugin is now being displayed by intellisense in the bower.json file edition. However, I was unable to display it in the visual search tool.

Do you have any suggestions for correcting this?

Thank you

**Comment by raphaelm22** [comment]
Plugin being displayed in visual studio

![image](https://user-images.githubusercontent.com/11078528/34224131-f3b34280-e5a8-11e7-882d-afe81810b51e.png)
