### ISSUE TITLE
Module loader friendly

### ISSUE THREAD

**Issue by galvarez421** [raphaelm22/jquery.serializeToJSON#12]
Thank you for this plugin -- I couldn't really find anything else like it online that is MVC form-friendly.

I think making the plugin friendly to module loaders would be helpful so that this plugin could be more compatible out of the box with modern module loaders/bundlers such as webpack, require.js, etc.

For example, you could use ES6 imports for source and UMD wrapper for distribution like Bootstrap seems to do. See https://github.com/twbs/bootstrap/blob/master/js/src/alert.js and https://github.com/twbs/bootstrap/blob/master/js/dist/alert.js and https://github.com/twbs/bootstrap/search?q=umd&unscoped_q=umd.

https://github.com/umdjs/umd shows some patterns for UMD wrapping.

**Comment by raphaelm22** [comment]
Hi @galvarez421 

Thanks for the tip, I'll try to implement

**Comment by raphaelm22** [comment]
Hi @galvarez421 
Tou could test version 1.3.0?

Thanks

**Comment by galvarez421** [comment]
I tested 1.2.3 vs 1.3.0 and 1.3.0 works with Webpack out of the box while 1.2.3 requires [shimming](https://webpack.js.org/guides/shimming/). Thanks!
