### ISSUE TITLE
Any tips on using serializeToJSON with large amount of data?

### ISSUE THREAD

**Issue by causefx** [raphaelm22/jquery.serializeToJSON#14]
I am serializing some forms on my app and once the data grows, serializeToJSON takes a few seconds to operate.  

Sample data of form:
```
data[action]: changeOrder
data[api]: api/?v1/settings/tab/editor/tabs
data[tabs][tab][1][id]: 1
data[tabs][tab][1][order]: 3
data[tabs][tab][1][originalOrder]: 3
data[tabs][tab][1][url_local]: null
data[tabs][tab][1][name]: Settings
data[tabs][tab][1][url]: api/?v1/settings/page
data[tabs][tab][1][ping_url]: 
data[tabs][tab][1][image]: fontawesome::cog
data[tabs][tab][1][timeout]: null
data[tabs][tab][1][timeout_ms]: 300000
data[tabs][tab][1][category_id]: 0
data[tabs][tab][1][group_id]: 1
data[tabs][tab][1][type]: 0
data[tabs][tab][1][default]: true
data[tabs][tab][1][enabled]: true
data[tabs][tab][1][splash]: false
data[tabs][tab][1][ping]: false
data[tabs][tab][1][preload]: false
```
There are about 50 records of the same-ish data. (Processing takes over 3 seconds)

![image](https://user-images.githubusercontent.com/16184466/64032754-007ad800-cb00-11e9-8d96-8060201e8359.png)

**Comment by raphaelm22** [comment]
Hi @causefx , could yout try the new version?

**Comment by causefx** [comment]
@raphaelm22 Doing it now :)

**Comment by causefx** [comment]
@raphaelm22 WOW.  Performance increased drastically.  From 3.02s to around 100-500 ms.  Well done, now I need to nail down some other jquery issues!  Thank you so much!
