### ISSUE TITLE
Bower not working

### ISSUE THREAD

**Issue by KANekT** [raphaelm22/jquery.serializeToJSON#3]
bower jquery.serializeToJSON#1.1.2       not-cached https://github.com/raphaelm22/jquery.serializeToJSON.git#1.1.2
bower jquery.serializeToJSON#1.1.2          resolve https://github.com/raphaelm22/jquery.serializeToJSON.git#1.1.2
bower jquery.serializeToJSON#1.1.2     ENORESTARGET No tag found that was able to satisfy 1.1.2
Additional error details:
No versions found in https://github.com/raphaelm22/jquery.serializeToJSON.git

**Comment by raphaelm22** [comment]
Could check again?

Thank you!

**Comment by KANekT** [comment]
Working
