### ISSUE TITLE
Serializing radio buttons can break

### ISSUE THREAD

**Issue by deammer** [raphaelm22/jquery.serializeToJSON#5]
Hi! I noticed an issue when serializing radio buttons with names such as `name="nest.radio.button`.

It's a simple fix - adding quotes around the name on line 98.
https://github.com/raphaelm22/jquery.serializeToJSON/blob/master/src/jquery.serializeToJSON.js#L98

**Comment by raphaelm22** [comment]
Hello @deammer . 
Would you mind to create a pull request?
