### ISSUE TITLE
Checkboxes and radio buttons: errors

### ISSUE THREAD

**Issue by donrolling** [raphaelm22/jquery.serializeToJSON#7]
Line 27 has this:
    if ($input.is(":checkbox")) {
        value = $($input.selector).prop('checked');
    }
the 'selector' is undefined.
this will fix it: 
    value = $input.prop('checked');

I'm not quite sure if there is a similar issue on line 22 (the only other place that selector is used):
    if ($input.is(":radio")) {
        value = $($input.selector + ":checked").val() || null;
    }
I don't know how to fix the radio button issue, because I don't have an example on hand right now.
I imagine it is pretty easy to fix, but wanted to let you know.

Thanks for this tool, it is helping me out today.

**Comment by raphaelm22** [comment]
Okay, I'll work on that.

Thanks for the feedback.

**Comment by raphaelm22** [comment]
The property [`selector`](https://api.jquery.com/selector/) was removed in 3.0 jQuery version

**Comment by raphaelm22** [comment]
@donrolling bug fixed
