### ISSUE TITLE
Multiple select input bug

### ISSUE THREAD

**Issue by joke1** [raphaelm22/jquery.serializeToJSON#8]
Your example tells me that the result of the CreditCardCompany input correctly should be:
`[
    "Company A",
    "Company C"
  ],`

Now check this out: https://jsfiddle.net/n2b6st03/
I've copy & paste your html - I've just added the selected attributes, so you just need to submit the form. The actual result for multiple select input fields are doubled:
`[
 [ "Company A", "Company B" ], 
 [ "Company A", "Company B" ] 
]
`

**Comment by raphaelm22** [comment]
@joke1 please, check de new version 1.2.1
